// This file needs to be generated by running:
//   1. ~/bin/firebase login
//   2. export PATH="$PATH:$HOME/.pub-cache/bin"
//   3. cd ~/rps_battle_arena && flutterfire configure
//
// For now, this is a placeholder that allows the app to compile
// without Firebase. The app will work in single-player mode.
// Multiplayer features require Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static bool get isConfigured => _isConfigured;
  static const bool _isConfigured = false;

  static FirebaseOptions get currentPlatform {
    // TODO: Replace with actual Firebase configuration
    // Run: flutterfire configure
    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        return _macos;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.android:
        return _android;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  // Placeholder values - replace after running flutterfire configure
  static const FirebaseOptions _macos = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'PLACEHOLDER',
    storageBucket: 'PLACEHOLDER',
    databaseURL: 'PLACEHOLDER',
    iosBundleId: 'com.example.rpsBattleArena',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'PLACEHOLDER',
    storageBucket: 'PLACEHOLDER',
    databaseURL: 'PLACEHOLDER',
    iosBundleId: 'com.example.rpsBattleArena',
  );

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'PLACEHOLDER',
    appId: 'PLACEHOLDER',
    messagingSenderId: 'PLACEHOLDER',
    projectId: 'PLACEHOLDER',
    storageBucket: 'PLACEHOLDER',
    databaseURL: 'PLACEHOLDER',
  );
}
